//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTPClient
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CalculationEntities : DbContext
    {
        public CalculationEntities()
            : base("name=CalculationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addition> Additions { get; set; }
        public virtual DbSet<Subtraction> Subtractions { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<Multiplication> Multiplications { get; set; }
    }
}
